services:
  - type: web
    name: ai-deployment-service
    env: docker
    repo: https://github.com/your-username/your-repo
    plan: standard
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ai-deployment-db
          property: connectionString
      - key: WORKERS
        value: 4
    healthCheckPath: /health
databases:
  - name: ai-deployment-db
    databaseName: ai_deployment
    plan: standard
